/**
 * Synchronizes the displays state object with the actual DOM elements.
 * 
 * This function performs a one-time lookup of jQuery selectors defined in the 
 * global 'displays' object and caches the resulting jQuery collections. 
 * This prevents repetitive DOM traversal during high-frequency combat events 
 * generated by collision detections.
 * 
 * @requires jQuery
 * @requires displays - Global object containing display configuration and element references.
 */
function initalize_displays() {
    displays.left_display.element = $(displays.left_display.selector);

    displays.right_display.element = $(displays.right_display.selector);    

    displays.center_display.element = $(displays.center_display.selector);
}


/**
 * Updates the numeric values of the left HUD display.
 * Initializes the static structure (labels and images) only once.
 */
function update_left_display() {
    const { hp, lives, critical_hp } = base_level_entities.bazis;
    const { a_bomb } = game_data.counters;
    const display = displays.left_display;
    const display_element = displays.left_display.element;

    const { HP, LIVES, ATOMIC, DIFF_COLOR, HP_CRITICAL} = UI_CONFIG.HUD.LEFT.VALUE_CLASSES;
    const { URL, WRAPPER_CLASS, IMG_CLASS, TXT_CLASS} = UI_CONFIG.HUD.LEFT.IMAGE;

    if (!display_element) {
        console.warn("UI Update deferred: wrapper not ready yet.");
        return;
    }
    
    if (display_element.find(`.${HP}`).length === 0) {
        display_element.html(`
            HEALTH :&nbsp; <span class='${HP} ${DIFF_COLOR}'></span> 
            &nbsp;/&nbsp; 
            LIVES :&nbsp; <span class='${LIVES}'></span>
            <span class='${WRAPPER_CLASS}'>
                <img src='${URL}' class='${IMG_CLASS}'>
                <span class='${TXT_CLASS} ${ATOMIC}'></span>
            </span>
        `);
    }

    if(!display.lives_val || display.lives_val.length === 0 ){
        display.hp_val = display_element.find(`.${HP}`);
        display.lives_val = display_element.find(`.${LIVES}`);
        display.atomic_val = display_element.find(`.${ATOMIC}`);
    }
  
    display.hp_val.text(hp);
    display.lives_val.text(lives);
    display.atomic_val.text(`: ${a_bomb}`);

    display.hp_val.toggleClass(HP_CRITICAL, hp <= critical_hp);
}

/**
 * Updates the numeric values of the right HUD display.
 * Initializes the static structure only once.
 */
function update_right_display() {
    const { score, killed, enemies } = game_data.counters;
    const display = displays.right_display;
    const display_element = displays.right_display.element;

    if (!display_element) {
        console.log("UI Update deferred: wrapper not ready yet.");
        return;
    }

    const { SCORE, KILLED, ENEMIES, DIFF_COLOR} = UI_CONFIG.HUD.RIGHT.VALUE_CLASSES;

    if( display_element.find(`.${SCORE}`).length === 0 ){
 display_element.html(`
        SCORE: &nbsp;<span class='${SCORE} ${DIFF_COLOR}'>${score}</span> 
        &nbsp;&nbsp; KILLED: &nbsp; <span class='${KILLED}'>${killed}</span>
        &nbsp; /&nbsp; <span class='${ENEMIES}'>${enemies}</span>`);      
}
if (!display.score_val || display.score_val.length === 0) {
    display.score_val = display_element.find(`.${SCORE}`);
    display.killed_val = display_element.find(`.${KILLED}`);
    display.enemies_val = display_element.find(`.${ENEMIES}`);
}
        display.score_val.text(score);
        display.killed_val.text(killed);
        display.enemies_val.text(enemies);    
}

/**
 * Displays a 'juicy' center screen notification for level ups or upgrades.
 * Uses CSS animations for hardware-accelerated scaling and glows.
 * 
 * @param {string} txt - The message to display (e.g., "WEAPON UPGRADE!").
 */
function update_center_display(txt) {
    const $container = displays.center_display.element;
    if(!$container) return;
    
    $container.stop(true, true).empty();

    const { MAIN, POP, EXIT} = UI_CONFIG.HUD.CENTER.CLASSES;
    const { DELAY, DURATION} = UI_CONFIG.HUD.CENTER.ANIMATION; 
    
    const $text = $(`<span class="${MAIN}">${txt}</span>`).appendTo($container);
    
    // Animation Start
    $text.addClass(POP);
    
    //  Schedule Exit: 800ms + 1500ms
    setTimeout(() => {
        if ($text.parent().length > 0) { 
            $text.addClass(EXIT);
            
            //  Final Cleanup
            setTimeout(() => {
                $container.empty();
            }, DURATION); 
        }
    }, DELAY);
}


// --- PROGRESS BAR ---
/**
 * Initializes the Boss health progress bar using the centralized displays object.
 * Setup is delayed to coordinate with level entry animations.
 */
function progress_bar_setup() {
    const boss_hp = boss_level_entities.boss.hp;

    setTimeout(function () {
        displays.progress_bar.instance = displays.center_display.element.progressbar({
            max: boss_hp,
            min: 0,
            value: boss_hp
        });

        displays.progress_bar.max_hp = boss_hp;

    }, UI_CONFIG.HUD.CENTER.PROGRESS_BAR.INIT_DELAY);
}

/**
 * Updates the Boss health bar UI. 
 * Triggered by collision events detected in boss_vs_bazis.js.
 * 
 * @param {number} boss_health - The current HP of the boss.
 */
function update_progressbar(boss_health) {
    const boss_data = boss_level_entities.boss;
    const bar_instance = displays.progress_bar.instance;
   
    if (!is_entity_valid(boss_data) || boss_health <= 0) {
        handle_victory_display(UI_CONFIG.HUD.CENTER.VICTORY.TEXT);
        return;
    }

    // 2. Update Widget
    if (bar_instance) {
        bar_instance.progressbar("value", boss_health);
        update_bar_color(boss_health);
    }
}

/**
* Sets progressbars' background color according to Boss health state.
*
*/
function update_bar_color(health) {
    const {GREEN_BG, ORANGE_BG, RED_BG, LOW_HP, CRITICAL_HP, VALUE_SELECTOR} =UI_CONFIG.HUD.CENTER.PROGRESS_BAR;

    let color = GREEN_BG; 
    if (health < CRITICAL_HP) color = RED_BG; 
    else if (health < LOW_HP) color = ORANGE_BG;
    
    $(VALUE_SELECTOR).css("background", color);
}

/**
 * Triggers the final victory sequence using CSS animations for performance.
 * Cleans up combat widgets and initiates the bonus score phase.
 */
function handle_victory_display(text) {
    const $container = displays.center_display.element;
    const bar_instance = displays.progress_bar.instance;

    const { DATA_KEY, METHOD_DESTROY, TEXT_CLASS, LIFE_BONUS_DELAY} = UI_CONFIG.HUD.CENTER.VICTORY;

    //  Cleanup Health Bar
    if (bar_instance && $container.data(DATA_KEY)) {
        $container.progressbar(METHOD_DESTROY);
        displays.progress_bar.instance = null;
    }
    
    //  Inject Animated Text
    $container.stop(true, true).empty();
    $(`<span class="${TEXT_CLASS}">${text}</span>`).appendTo($container);

    //  Bonus Calculation
    setTimeout(() => {
        check_for_life_bonus();
    }, LIFE_BONUS_DELAY);
}

/**
 * Calculates and animates a score bonus for remaining player lives at the end of a boss fight.
 * 
 * If the player has more than one life remaining, the function:
 * 1. Waits for a thematic delay.
 * 2. Calculates total bonus based on (lives - 1) * 5000.
 * 3. Clears the center UI panel and injects a live-counting display.
 * 4. Iteratively increments the displayed bonus value in 100-point steps.
 * 5. Updates the global score state and the HUD display.
 * 
 * @async
 * @function check_for_life_bonus
 * @requires displays - Access to the centralized center_display element.
 * @requires base_level_entities - Access to player (Bazis) life count.
 * @requires game_data - Access to global score and counters.
 * @requires update_right_display - Function to refresh the Score HUD.
 * @returns {Promise<void>} Resolves when the counting animation and score update are complete.
 */
async function check_for_life_bonus() {
    if (base_level_entities.bazis.lives <= 1) return;

    const { INITIAL_DELAY, TICK_RATE, BONUS_SCORE_PER_LIFE, COUNTER_INCREMENT,
            CONTAINER_CLASS, BONUS_CLASS } = UI_CONFIG.HUD.CENTER.LIFE_BONUS;
            
    const lifebonus = (base_level_entities.bazis.lives - 1) * BONUS_SCORE_PER_LIFE;
    game_data.counters.score += lifebonus;
    
    const $container = displays.center_display.element;
            
    await new Promise(resolve => setTimeout(resolve, INITIAL_DELAY));
    
    $container.empty();
    
    $(`<div class='${CONTAINER_CLASS}'>Life bonus :</div>`).appendTo($container);
    const $center_display = $(`<div class='${BONUS_CLASS}'>0</div>`).appendTo($container);
    
    let bonus_counter = 0;
    while (bonus_counter < lifebonus) {
        bonus_counter += COUNTER_INCREMENT;
        $center_display.text(bonus_counter);
        await new Promise(r => setTimeout(r, TICK_RATE));
    }

    update_right_display();
}
