const COLLISION_CONFIG = {
    EMP_STRIKE_ZONE_Y_PX: 60,
    EMP_STRIKE_ZONE_X_PX: 30,
    BAZIS_DAMAGE_MULTIPLIER: 1.5,
    EMP_COOLDOWN_MS: 500,

     ENTITY_TYPES : {
        ENEMY: GAME_ENTITY_TYPES.ENEMY,
        BOUNTY: GAME_ENTITY_TYPES.BOUNTY,
        BAZIS: GAME_ENTITY_TYPES.BAZIS,
        BOSS: GAME_ENTITY_TYPES.BOSS
    },
    WEAPON_TYPES: {
        PRIMARY_SHOT_TYPES: Object.values(BAZIS_SHOTS_CONFIG).map(config => config.TYPE),
        LAZER_TYPES: [BAZIS_SHOTS_CONFIG.SINGLE_LAZER_SHOT.TYPE, BAZIS_SHOTS_CONFIG.DUAL_LAZER_SHOT.TYPE],
        ENEMY_SHOT: GAME_ENTITY_TYPES.ENEMY_SHOT,
        BOSS_SHOT_TYPES: Object.values(BOSS_SHOTS_CONFIG).map(config => config.TYPE),
        BOSS_LAZER_SHOT: BOSS_SHOTS_CONFIG.LAZER_SHOT.TYPE
    }
}

