const COLLISION_CONFIG = {
    BAZIS_KICK_BACK_y_OFFSET: 40,
    ANIM_DURATION: 200,
    EMP_STRIKE_ZONE_Y_PX: 60,
    EMP_STRIKE_ZONE_X_PX: 30,
    BAZIS_DAMAGE_MULTIPLIER: 2,
    EMP_COOLDOWN_MS: 500
}